// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM7HpFfRbIBWlv1G1USO77yzNZZ6FvMX4',
    appId: '1:772242563754:web:221528cf548b4828aca6d3',
    messagingSenderId: '772242563754',
    projectId: 'dam-u4-p1-ammg',
    authDomain: 'dam-u4-p1-ammg.firebaseapp.com',
    storageBucket: 'dam-u4-p1-ammg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0C_9qtHkp-AuUuV4F074_CZFBBJ2BBw8',
    appId: '1:772242563754:android:a91bb9ba93dd6abfaca6d3',
    messagingSenderId: '772242563754',
    projectId: 'dam-u4-p1-ammg',
    storageBucket: 'dam-u4-p1-ammg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGwzH3PXGr_i5i8xLAnwY8IBY7RLhPwQU',
    appId: '1:772242563754:ios:71407cdfb22443e6aca6d3',
    messagingSenderId: '772242563754',
    projectId: 'dam-u4-p1-ammg',
    storageBucket: 'dam-u4-p1-ammg.appspot.com',
    iosClientId: '772242563754-mpththe22iosrl6rh9ugb1n58g8b6dc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Practica1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGwzH3PXGr_i5i8xLAnwY8IBY7RLhPwQU',
    appId: '1:772242563754:ios:71407cdfb22443e6aca6d3',
    messagingSenderId: '772242563754',
    projectId: 'dam-u4-p1-ammg',
    storageBucket: 'dam-u4-p1-ammg.appspot.com',
    iosClientId: '772242563754-mpththe22iosrl6rh9ugb1n58g8b6dc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Practica1',
  );
}
